version: "2"
run:
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: disable

linters:
  default: all
  disable:
    - revive
    - exhaustruct
    - tagliatelle
    # deprecated
    - wsl
    - depguard
  settings:
    errcheck:
      check-blank: false
      exclude-functions:
        # Used in HTTP handlers, any error is handled by the server itself.
        - (net/http.ResponseWriter).Write
        # Never check the logger error.
        - (github.com/go-kit/log.Logger).Log
        - fmt:.*
    nolintlint:
      require-specific: true
  exclusions:
    paths:
      - examples/
      - ".*_test.go"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
