# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: gopensky.spec

jobs:
  - job: copr_build
    trigger: commit
    branch: main
    owner: navidys
    project: gopensky
    enable_net: true
    srpm_build_deps:
      - make
      - openssl-devel
      - rpkg
    actions:
      post-upstream-clone:
        - "rpkg spec --outdir ./"

      fix-spec-file:
        "bash .packit.sh"
