name: validate pull requests
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  DCO-check:
    runs-on: ubuntu-latest
    steps:
      - name: get pr commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: DCO check
        uses: tim-actions/dco@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}

      - name: check subject line length
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^.{0,72}(\n.*)*$'
          error: 'Subject too long (max 72)'

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          skip: ./.git,./vendor,*_test.go,go.sum,go.mod

  vendoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - uses: actions/checkout@v3
      - run: |
          go mod tidy
          go mod vendor
          go mod verify
          bash ./hack/tree_status.sh

  golangci-lint_fmt:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - uses: actions/checkout@v3
      - run: |
          dnf -y install make gcc glib2-devel glibc-static golang
          make .install.golangci-lint
          make lint
          make gofmt

  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.22
      uses: actions/setup-go@v1
      with:
        go-version: 1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        export GOBIN=$(pwd)/bin/
        make .install.ginkgo

  goreportcard:
    name: update reportcard
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: creekorful/goreportcard-action@v1.0
